### ISSUE TITLE
android:allowBackup and android:supportsRtl

### ISSUE THREAD

**Issue by Waboodoo** [bukalapak/url-router#9]
I was wondering why the manifest declares `android:allowBackup="true"` and `android:supportsRtl="true"`. I don't see how they are relevant to the library. In my project they caused problems because they conflicted with my app's own manifest, forcing me to explicitly override them. This is a valid workaround but I think it would be much nicer if it weren't necessary. Do you think it would be possible to drop these 2 declarations?

**Comment by mrhabibi** [comment]
Hello @Waboodoo. Yes they shouldn't be relevant, I didn't know them existed. Could you please make PR for that?

**Comment by Waboodoo** [comment]
Done: https://github.com/bukalapak/url-router/pull/10

**Comment by rahulpahuja** [comment]
android:allowBackup
Whether to allow the application to participate in the backup and restore infrastructure. If this attribute is set to false, no backup or restore of the application will ever be performed, even by a full-system backup that would otherwise cause all application data to be saved via adb. The default value of this attribute is true.



android:supportsRtl
Declares whether your application is willing to support right-to-left (RTL) layouts.
If set to true and targetSdkVersion is set to 17 or higher, various RTL APIs will be activated and used by the system so your app can display RTL layouts. If set to false or if targetSdkVersion is set to 16 or lower, the RTL APIs will be ignored or will have no effect and your app will behave the same regardless of the layout direction associated to the user's Locale choice (your layouts will always be left-to-right).

The default value of this attribute is false.

This attribute was added in API level 17.

Source:https://developer.android.com/guide/topics/manifest/application-element


What i believe from the above is that the android:supportsRtl might be causing that issue because it needs change in api level , and these can be dropped of there is no problem with that 

Hope this helps

**Comment by Waboodoo** [comment]
@rahulpahuja My problem is that these attributes clash with the same ones defined in my app's manifest. This is no big problem as I can explictly override them, but it would be even better if I didn't have to do this workaround.

**Comment by mrhabibi** [comment]
Hi @Waboodoo sorry I was slow response. Can you stay with your workaround for awhile? I'm now working for the next version of Url Router in another repo, with a lot of improvements and features. I'm going to publish it next week and this repo will be deprecated.

**Comment by mrhabibi** [comment]
Here we go the repo: [Neuro project](https://github.com/bukalapak/neuro)
